..-spring.application.name=backend

# Database Connection

spring.datasource.url=jdbc:postgresql://db.wuuzgwgtqvtbaqjeloig.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Ekadarsh123@

# JPA Settings
spring.jpa.hibernate.ddl-auto=update

# External APIs
finnhub.api.key=d211q5pr01qvvf1klih0d211q5pr01qvvf1klihg


